// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: internal/pkg/protobuf/cpupinning/cpupinning.proto

package cpupinning

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CPUPinning_ApplyPinning_FullMethodName  = "/CPUPinning/ApplyPinning"
	CPUPinning_RemovePinning_FullMethodName = "/CPUPinning/RemovePinning"
)

// CPUPinningClient is the client API for CPUPinning service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CPUPinningClient interface {
	ApplyPinning(ctx context.Context, in *ApplyPinningRequest, opts ...grpc.CallOption) (*Response, error)
	RemovePinning(ctx context.Context, in *RemovePinningRequest, opts ...grpc.CallOption) (*Response, error)
}

type cPUPinningClient struct {
	cc grpc.ClientConnInterface
}

func NewCPUPinningClient(cc grpc.ClientConnInterface) CPUPinningClient {
	return &cPUPinningClient{cc}
}

func (c *cPUPinningClient) ApplyPinning(ctx context.Context, in *ApplyPinningRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, CPUPinning_ApplyPinning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUPinningClient) RemovePinning(ctx context.Context, in *RemovePinningRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, CPUPinning_RemovePinning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CPUPinningServer is the server API for CPUPinning service.
// All implementations must embed UnimplementedCPUPinningServer
// for forward compatibility.
type CPUPinningServer interface {
	ApplyPinning(context.Context, *ApplyPinningRequest) (*Response, error)
	RemovePinning(context.Context, *RemovePinningRequest) (*Response, error)
	mustEmbedUnimplementedCPUPinningServer()
}

// UnimplementedCPUPinningServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCPUPinningServer struct{}

func (UnimplementedCPUPinningServer) ApplyPinning(context.Context, *ApplyPinningRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPinning not implemented")
}
func (UnimplementedCPUPinningServer) RemovePinning(context.Context, *RemovePinningRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePinning not implemented")
}
func (UnimplementedCPUPinningServer) mustEmbedUnimplementedCPUPinningServer() {}
func (UnimplementedCPUPinningServer) testEmbeddedByValue()                    {}

// UnsafeCPUPinningServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CPUPinningServer will
// result in compilation errors.
type UnsafeCPUPinningServer interface {
	mustEmbedUnimplementedCPUPinningServer()
}

func RegisterCPUPinningServer(s grpc.ServiceRegistrar, srv CPUPinningServer) {
	// If the following call pancis, it indicates UnimplementedCPUPinningServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CPUPinning_ServiceDesc, srv)
}

func _CPUPinning_ApplyPinning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPinningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUPinningServer).ApplyPinning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CPUPinning_ApplyPinning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUPinningServer).ApplyPinning(ctx, req.(*ApplyPinningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUPinning_RemovePinning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePinningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUPinningServer).RemovePinning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CPUPinning_RemovePinning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUPinningServer).RemovePinning(ctx, req.(*RemovePinningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CPUPinning_ServiceDesc is the grpc.ServiceDesc for CPUPinning service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CPUPinning_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CPUPinning",
	HandlerType: (*CPUPinningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyPinning",
			Handler:    _CPUPinning_ApplyPinning_Handler,
		},
		{
			MethodName: "RemovePinning",
			Handler:    _CPUPinning_RemovePinning_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pkg/protobuf/cpupinning/cpupinning.proto",
}
