kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: daemon
  namespace: system
spec:
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      name: daemon
      labels:
        app: daemon
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      serviceAccountName: controller-manager
      hostNetwork: true
      containers:
        - name: actimanager-daemon
          image: stefanaki/actimanager:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          securityContext:
            privileged: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - all
          args:
            - '--node-name=$(NODE_NAME)'
#           - '--container-runtime=docker'
            - '--container-runtime=containerd'
            - '--cgroups-path=/cgroup'
            - '--cgroups-driver=systemd'
            - '--reconcile-period=15s'
            - '--verbosity=3'
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: host
              mountPath: /cgroup
          resources:
            limits:
              cpu: "4"
              memory: "512M"
            requests:
              cpu: "1"
              memory: "64M"
          readinessProbe:
            grpc:
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 8089
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: host
          hostPath:
            path: /sys/fs/cgroup