# permissions for end users to view nodecputopologies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodecputopology-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: actimanager
    app.kubernetes.io/part-of: actimanager
    app.kubernetes.io/managed-by: kustomize
  name: nodecputopology-viewer-role
rules:
- apiGroups:
  - cslab.ece.ntua.gr
  resources:
  - nodecputopologies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cslab.ece.ntua.gr
  resources:
  - nodecputopologies/status
  verbs:
  - get
