apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /home/georgios/.kube/config
profiles:
  - schedulerName: maestro
    plugins:
      preFilter:
        enabled:
          - name: PodIsolation
      score:
        enabled:
          - name: PodIsolation
      filter:
        enabled:
          - name: PodIsolation
      postBind:
        enabled:
          - name: PodIsolation
