apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /home/georgios/.kube/config
profiles:
  - schedulerName: maestro
    plugins:
      preFilter:
        enabled:
          - name: WorkloadAware
      filter:
        enabled:
          - name: TaintToleration
          - name: WorkloadAware
      score:
        enabled:
          - name: WorkloadAware
      bind:
        enabled:
          - name: WorkloadAware
        disabled:
            - name: '*'
    pluginConfig:
      - name: WorkloadAware
        args:
          policy: Balanced
          features:
            - PhysicalCores
#            - BestEffortSharedCPUs
#            - MemoryBoundExclusiveSockets
