FROM golang:1.22.2 as builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY cmd/ cmd/
COPY api/ api/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o daemon cmd/daemon/main.go cmd/daemon/server.go

FROM ubuntu
WORKDIR /
COPY --from=builder /workspace/daemon .
USER root:root

ENTRYPOINT ["/daemon"]
