apiVersion: cslab.ece.ntua.gr/v1alpha1
kind: PodCpuBinding
metadata:
  labels:
    app.kubernetes.io/name: podcpubinding
    app.kubernetes.io/instance: podcpubinding-sample
    app.kubernetes.io/part-of: actimanager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: actimanager
  name: bind
  namespace: benchmarks
spec:
  exclusivenessLevel: Cpu
  podName: run-parsec-blackscholes-gcc-4-native-cljhc
  cpuSet:
  - cpuId: 12
  - cpuId: 13

