apiVersion: cslab.ece.ntua.gr/v1alpha1
kind: PodCpuBinding
metadata:
  name: binding-1
  namespace: benchmarks
spec:
  exclusivenessLevel: Core
  podName: run-parsec-blackscholes-gcc-4-native-lh672
  cpuSet:
  - cpuId: 4
  - cpuId: 7

