apiVersion: v1
kind: Pod
metadata:
  name: stress-pod-node-2
  namespace: benchmarks
spec:
  nodeName: minikube-m02
  containers:
  - image: gcr.io/google-containers/stress:v1
    args: ["-cpus", "8"]
    name: stress-container
  restartPolicy: "Never"
