apiVersion: v1
kind: Pod
metadata:
  name: benchpod-5
  namespace: benchmarks
spec:
  schedulerName: podisolation
  restartPolicy: Never
  containers:
  - name: benchmark
    image: spirals/parsec-3.0
    resources:
      requests:
        cpu: "2000m"
      limits:
        cpu: "2000m"
    command:
    - /bin/bash
    - "-c"
    - sleep 9999999999999999

