//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	config "cslab.ece.ntua.gr/actimanager/api/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddConversionFunc((*config.WorkloadAwareArgs)(nil), (*WorkloadAwareArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_WorkloadAwareArgs_To_v1_WorkloadAwareArgs(a.(*config.WorkloadAwareArgs), b.(*WorkloadAwareArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*WorkloadAwareArgs)(nil), (*config.WorkloadAwareArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_WorkloadAwareArgs_To_config_WorkloadAwareArgs(a.(*WorkloadAwareArgs), b.(*config.WorkloadAwareArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_WorkloadAwareArgs_To_config_WorkloadAwareArgs(in *WorkloadAwareArgs, out *config.WorkloadAwareArgs, s conversion.Scope) error {
	// WARNING: in.Policy requires manual conversion: inconvertible types (*cslab.ece.ntua.gr/actimanager/api/config/v1.WorkloadAwarePolicy vs cslab.ece.ntua.gr/actimanager/api/config.WorkloadAwarePolicy)
	// WARNING: in.Features requires manual conversion: inconvertible types (*[]cslab.ece.ntua.gr/actimanager/api/config/v1.Feature vs []cslab.ece.ntua.gr/actimanager/api/config.Feature)
	return nil
}

func autoConvert_config_WorkloadAwareArgs_To_v1_WorkloadAwareArgs(in *config.WorkloadAwareArgs, out *WorkloadAwareArgs, s conversion.Scope) error {
	// WARNING: in.Policy requires manual conversion: inconvertible types (cslab.ece.ntua.gr/actimanager/api/config.WorkloadAwarePolicy vs *cslab.ece.ntua.gr/actimanager/api/config/v1.WorkloadAwarePolicy)
	// WARNING: in.Features requires manual conversion: inconvertible types ([]cslab.ece.ntua.gr/actimanager/api/config.Feature vs *[]cslab.ece.ntua.gr/actimanager/api/config/v1.Feature)
	return nil
}
