// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: cpu_pinning_daemon.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExclusivenessLevel int32

const (
	ExclusivenessLevel_CPU    ExclusivenessLevel = 0
	ExclusivenessLevel_CORE   ExclusivenessLevel = 1
	ExclusivenessLevel_SOCKET ExclusivenessLevel = 2
	ExclusivenessLevel_NUMA   ExclusivenessLevel = 3
)

// Enum value maps for ExclusivenessLevel.
var (
	ExclusivenessLevel_name = map[int32]string{
		0: "CPU",
		1: "CORE",
		2: "SOCKET",
		3: "NUMA",
	}
	ExclusivenessLevel_value = map[string]int32{
		"CPU":    0,
		"CORE":   1,
		"SOCKET": 2,
		"NUMA":   3,
	}
)

func (x ExclusivenessLevel) Enum() *ExclusivenessLevel {
	p := new(ExclusivenessLevel)
	*p = x
	return p
}

func (x ExclusivenessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExclusivenessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_cpu_pinning_daemon_proto_enumTypes[0].Descriptor()
}

func (ExclusivenessLevel) Type() protoreflect.EnumType {
	return &file_cpu_pinning_daemon_proto_enumTypes[0]
}

func (x ExclusivenessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExclusivenessLevel.Descriptor instead.
func (ExclusivenessLevel) EnumDescriptor() ([]byte, []int) {
	return file_cpu_pinning_daemon_proto_rawDescGZIP(), []int{0}
}

type CpuSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu []int32 `protobuf:"varint,1,rep,packed,name=cpu,proto3" json:"cpu,omitempty"`
}

func (x *CpuSet) Reset() {
	*x = CpuSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpu_pinning_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpuSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuSet) ProtoMessage() {}

func (x *CpuSet) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_pinning_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuSet.ProtoReflect.Descriptor instead.
func (*CpuSet) Descriptor() ([]byte, []int) {
	return file_cpu_pinning_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *CpuSet) GetCpu() []int32 {
	if x != nil {
		return x.Cpu
	}
	return nil
}

type Pod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *Pod) Reset() {
	*x = Pod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpu_pinning_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_pinning_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_cpu_pinning_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *Pod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ApplyPinningRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pod                *Pod               `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	CpuSet             *CpuSet            `protobuf:"bytes,2,opt,name=cpuSet,proto3" json:"cpuSet,omitempty"`
	ExclusivenessLevel ExclusivenessLevel `protobuf:"varint,3,opt,name=exclusivenessLevel,proto3,enum=ExclusivenessLevel" json:"exclusivenessLevel,omitempty"`
}

func (x *ApplyPinningRequest) Reset() {
	*x = ApplyPinningRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpu_pinning_daemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyPinningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPinningRequest) ProtoMessage() {}

func (x *ApplyPinningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_pinning_daemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPinningRequest.ProtoReflect.Descriptor instead.
func (*ApplyPinningRequest) Descriptor() ([]byte, []int) {
	return file_cpu_pinning_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyPinningRequest) GetPod() *Pod {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *ApplyPinningRequest) GetCpuSet() *CpuSet {
	if x != nil {
		return x.CpuSet
	}
	return nil
}

func (x *ApplyPinningRequest) GetExclusivenessLevel() ExclusivenessLevel {
	if x != nil {
		return x.ExclusivenessLevel
	}
	return ExclusivenessLevel_CPU
}

type ApplyPinningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplyPinningResponse) Reset() {
	*x = ApplyPinningResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpu_pinning_daemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyPinningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPinningResponse) ProtoMessage() {}

func (x *ApplyPinningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_pinning_daemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPinningResponse.ProtoReflect.Descriptor instead.
func (*ApplyPinningResponse) Descriptor() ([]byte, []int) {
	return file_cpu_pinning_daemon_proto_rawDescGZIP(), []int{3}
}

type RemovePinningRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemovePinningRequest) Reset() {
	*x = RemovePinningRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpu_pinning_daemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePinningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePinningRequest) ProtoMessage() {}

func (x *RemovePinningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_pinning_daemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePinningRequest.ProtoReflect.Descriptor instead.
func (*RemovePinningRequest) Descriptor() ([]byte, []int) {
	return file_cpu_pinning_daemon_proto_rawDescGZIP(), []int{4}
}

type RemovePinningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemovePinningResponse) Reset() {
	*x = RemovePinningResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpu_pinning_daemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePinningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePinningResponse) ProtoMessage() {}

func (x *RemovePinningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_pinning_daemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePinningResponse.ProtoReflect.Descriptor instead.
func (*RemovePinningResponse) Descriptor() ([]byte, []int) {
	return file_cpu_pinning_daemon_proto_rawDescGZIP(), []int{5}
}

type UpdatePinningRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePinningRequest) Reset() {
	*x = UpdatePinningRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpu_pinning_daemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePinningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePinningRequest) ProtoMessage() {}

func (x *UpdatePinningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_pinning_daemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePinningRequest.ProtoReflect.Descriptor instead.
func (*UpdatePinningRequest) Descriptor() ([]byte, []int) {
	return file_cpu_pinning_daemon_proto_rawDescGZIP(), []int{6}
}

type UpdatePinningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePinningResponse) Reset() {
	*x = UpdatePinningResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpu_pinning_daemon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePinningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePinningResponse) ProtoMessage() {}

func (x *UpdatePinningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_pinning_daemon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePinningResponse.ProtoReflect.Descriptor instead.
func (*UpdatePinningResponse) Descriptor() ([]byte, []int) {
	return file_cpu_pinning_daemon_proto_rawDescGZIP(), []int{7}
}

var File_cpu_pinning_daemon_proto protoreflect.FileDescriptor

var file_cpu_pinning_daemon_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x70, 0x75, 0x5f, 0x70, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x06, 0x43, 0x70,
	0x75, 0x53, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x03, 0x63, 0x70, 0x75, 0x22, 0x47, 0x0a, 0x03, 0x50, 0x6f, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22,
	0x93, 0x01, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x03, 0x70, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x50, 0x6f, 0x64, 0x52, 0x03, 0x70, 0x6f, 0x64, 0x12,
	0x1f, 0x0a, 0x06, 0x63, 0x70, 0x75, 0x53, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x43, 0x70, 0x75, 0x53, 0x65, 0x74, 0x52, 0x06, 0x63, 0x70, 0x75, 0x53, 0x65, 0x74,
	0x12, 0x43, 0x0a, 0x12, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73,
	0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x45,
	0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x12, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x16, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x50, 0x69,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a,
	0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16,
	0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a,
	0x3d, 0x0a, 0x12, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x43, 0x4f, 0x52, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x4f, 0x43, 0x4b,
	0x45, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4d, 0x41, 0x10, 0x03, 0x32, 0xcf,
	0x01, 0x0a, 0x10, 0x43, 0x70, 0x75, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x50, 0x69, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x50, 0x69, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3e, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x12, 0x15, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3e, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x12, 0x15, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cpu_pinning_daemon_proto_rawDescOnce sync.Once
	file_cpu_pinning_daemon_proto_rawDescData = file_cpu_pinning_daemon_proto_rawDesc
)

func file_cpu_pinning_daemon_proto_rawDescGZIP() []byte {
	file_cpu_pinning_daemon_proto_rawDescOnce.Do(func() {
		file_cpu_pinning_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_cpu_pinning_daemon_proto_rawDescData)
	})
	return file_cpu_pinning_daemon_proto_rawDescData
}

var file_cpu_pinning_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cpu_pinning_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cpu_pinning_daemon_proto_goTypes = []interface{}{
	(ExclusivenessLevel)(0),       // 0: ExclusivenessLevel
	(*CpuSet)(nil),                // 1: CpuSet
	(*Pod)(nil),                   // 2: Pod
	(*ApplyPinningRequest)(nil),   // 3: ApplyPinningRequest
	(*ApplyPinningResponse)(nil),  // 4: ApplyPinningResponse
	(*RemovePinningRequest)(nil),  // 5: RemovePinningRequest
	(*RemovePinningResponse)(nil), // 6: RemovePinningResponse
	(*UpdatePinningRequest)(nil),  // 7: UpdatePinningRequest
	(*UpdatePinningResponse)(nil), // 8: UpdatePinningResponse
}
var file_cpu_pinning_daemon_proto_depIdxs = []int32{
	2, // 0: ApplyPinningRequest.pod:type_name -> Pod
	1, // 1: ApplyPinningRequest.cpuSet:type_name -> CpuSet
	0, // 2: ApplyPinningRequest.exclusivenessLevel:type_name -> ExclusivenessLevel
	3, // 3: CpuPinningDaemon.ApplyPinning:input_type -> ApplyPinningRequest
	5, // 4: CpuPinningDaemon.RemovePinning:input_type -> RemovePinningRequest
	7, // 5: CpuPinningDaemon.UpdatePinning:input_type -> UpdatePinningRequest
	4, // 6: CpuPinningDaemon.ApplyPinning:output_type -> ApplyPinningResponse
	6, // 7: CpuPinningDaemon.RemovePinning:output_type -> RemovePinningResponse
	8, // 8: CpuPinningDaemon.UpdatePinning:output_type -> UpdatePinningResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cpu_pinning_daemon_proto_init() }
func file_cpu_pinning_daemon_proto_init() {
	if File_cpu_pinning_daemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cpu_pinning_daemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpuSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cpu_pinning_daemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cpu_pinning_daemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyPinningRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cpu_pinning_daemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyPinningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cpu_pinning_daemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePinningRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cpu_pinning_daemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePinningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cpu_pinning_daemon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePinningRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cpu_pinning_daemon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePinningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cpu_pinning_daemon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cpu_pinning_daemon_proto_goTypes,
		DependencyIndexes: file_cpu_pinning_daemon_proto_depIdxs,
		EnumInfos:         file_cpu_pinning_daemon_proto_enumTypes,
		MessageInfos:      file_cpu_pinning_daemon_proto_msgTypes,
	}.Build()
	File_cpu_pinning_daemon_proto = out.File
	file_cpu_pinning_daemon_proto_rawDesc = nil
	file_cpu_pinning_daemon_proto_goTypes = nil
	file_cpu_pinning_daemon_proto_depIdxs = nil
}
